---
- name: Start NetIM Audit
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios

  # The {{ rule_id }} variable corresponds to the netim rule that needs to be
  # fixed, passed as an extravar

  tasks:
    - debug:
        msg: "Kicking off Multi Audit Workflow on {{inventory_hostname}}"
