---

- name: Gather Interface Names
  ios_facts:
    gather_subset: interfaces
  register: output

- set_fact:
    interfaces_list: "{{ansible_net_interfaces.keys()}}"

- debug:
    var: interfaces_list

# - name: configure interface
#   ios_interface:
#       name: "{{ item }}"
#       speed: "{{ speed }}"
#       duplex: "{{ duplex }}"
#       mtu: "{{ mtu }}"
#   loop: "{{ interfaces_list }}"
#   when: Fast in interfaces_list

- debug:
    var: item
  loop: "{{ interfaces_list }}"
  when: '"Fast*" in interfaces_list'


